{% set name = "nrtk-explorer" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nrtk_explorer-{{ version }}.tar.gz
  sha256: 9b689454f15607a23bd6b81a887f402cb209a7fd983f58a3811b3115e121f16a

build:
  entry_points:
    - nrtk-explorer = nrtk_explorer.app.main:main
    - nrtk-explorer-embeddings = nrtk_explorer.app.embeddings:main
    - nrtk-explorer-tranforms = nrtk_explorer.app.transforms:main
    - nrtk-explorer-filtering = nrtk_explorer.app.filtering:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - nodejs
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - accelerate
    - kwcoco
    - pybsm >=0.6,<=0.9
    - nrtk
    - numpy
    - pillow
    - python >={{ python_min }}
    - pytorch
    - scikit-image
    - scikit-learn ==1.5.2
    - tabulate
    - timm
    - torchvision
    - trame >=3.7
    - trame-client >=2.15.0
    - trame-quasar
    - trame-server >=2.15.0
    - trame-annotations
    - transformers
    - umap-learn
    - datasets
    - pillow
    - torchvision
    - imageio

test:
  imports:
    - nrtk_explorer
  commands:
    - pip check
    - pytest -v .
    - nrtk-explorer --help
    - nrtk-explorer-embeddings --help
    - nrtk-explorer-tranforms --help
    - nrtk-explorer-filtering --help
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://pypi.org/project/nrtk-explorer/
  dev_url: https://github.com/Kitware/nrtk-explorer
  summary: Model Visualizer
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vicentebolea
    - jourdain
