{% set name = "nrtk-explorer" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nrtk_explorer-{{ version }}.tar.gz
  sha256: 8210158782b6085d8ef29a61fb6f9259332d31b8dd9645b4b1a4023d512f1bea

build:
  entry_points:
    - nrtk-explorer = nrtk_explorer.app:main
    - nrtk-explorer-embeddings = nrtk_explorer.app.embeddings:embeddings
    - nrtk-explorer-tranforms = nrtk_explorer.app.transforms:transforms
    - nrtk-explorer-filtering = nrtk_explorer.app.filtering:filtering
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - nodejs
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - accelerate
    - nrtk
    - numpy
    - pillow
    - python >=3.7
    - pytorch
    - scikit-image
    - scikit-learn ==1.4.2
    - smqtk-classifier ==0.19.0
    - smqtk-core ==0.19.0
    - smqtk-dataprovider ==0.18.0
    - smqtk-descriptors ==0.19.0
    - smqtk-detection ==0.20.1
    - smqtk-image-io ==0.17.1
    - tabulate
    - timm
    - torchvision
    - trame
    - trame-client >=2.15.0
    - trame-quasar
    - trame-server >=2.15.0
    - transformers
    - ubelt ==1.3.5
    - umap-learn

test:
  imports:
    - nrtk_explorer
  commands:
    - pip check
    - pytest -v .
    - nrtk-explorer --help
    - nrtk-explorer-embeddings --help
    - nrtk-explorer-tranforms --help
    - nrtk-explorer-filtering --help
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://pypi.org/project/nrtk-explorer/
  dev_url: https://github.com/Kitware/nrtk-explorer
  summary: Model Visualizer
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vicentebolea
